apiVersion: v2
name: alura-foods-app
description: Um Helm Chart, para efetuar deploy dos micros-servi√ßos do alura foods.
type: application
version: 1.0.0
appVersion: 0.0.1

dependencies:
  - name: mysql
    version: "11.1.7"
    repository: https://charts.bitnami.com/bitnami
